# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GEGqwA6I9TCuaV_vy0Q8kP3W2dX1FJlH
"""

## 1. Escrever o arquivo app.py (O Dashboard simplificado)
with open('app.py', 'w') as f:
    f.write("""
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Dashboard MK", layout="wide")

try:
    # Carregando os dados que você já gerou
    df = pd.read_csv('ecommerce_products_enriched.csv')

    st.title("📊 Dashboard MK E-commerce")

    # KPIs
    c1, c2 = st.columns(2)
    c1.metric("Faturamento Total", f"R$ {df['price'].sum():,.2f}")
    c2.metric("Ticket Médio", f"R$ {df['price'].mean():.2f}")

    # Gráfico simples de Categorias
    st.subheader("Vendas por Categoria")
    fig = px.bar(df.groupby('category')['price'].sum().reset_index(), x='category', y='price')
    st.plotly_chart(fig, use_container_width=True)

    # Tabela com a IA
    st.subheader("🔍 Atributos Extraídos por IA")
    st.dataframe(df[['title', 'material', 'tecnologia']])

except Exception as e:
    st.error(f"Erro: {e}. Certifique-se que o arquivo 'ecommerce_products_enriched.csv' existe.")
    """)

# 2. Instalar o Localtunnel (Necessário apenas uma vez)
!npm install -g localtunnel

# 3. Rodar o Streamlit em segundo plano e abrir o Túnel
import subprocess
import os

# Inicia o streamlit
subprocess.Popen(['streamlit', 'run', 'app.py', '--server.port', '8501'])

# Exibe o IP público (Você precisará desse número para o túnel)
print("\n--- PASSO IMPORTANTE ---")
print("Se o link abaixo pedir um 'Endpoint IP', use este número:")
!curl ipv4.icanhazip.com
print("------------------------\n")

# Inicia o túnel
!npx localtunnel --port 8501