# -*- coding: utf-8 -*-
"""IA_FEATURES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3Njh53HrhyosxjKL0d9JMyTnwD5RLBe
"""

import google.generativeai as genai
import pandas as pd
import time
import json

# 1. Configuração da API
GOOGLE_API_KEY = "CHAVE_Api"
genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

df_products = pd.read_csv("ecommerce_products.csv")
enriched_data = []

BATCH_SIZE = 10
SLEEP_BETWEEN_CALLS = 15
MAX_RETRIES = 5

print(f" Iniciando processamento de {len(df_products)} produtos...")

# 2. Loop por batch
for start in range(0, len(df_products), BATCH_SIZE):
    end = start + BATCH_SIZE
    batch_df = df_products.iloc[start:end]
    batch_records = batch_df.to_dict(orient="records")

    prompt = f"""
Você receberá uma LISTA de produtos.
Retorne APENAS um JSON ARRAY onde cada item segue exatamente este formato:

{{
  "product_id": int,
  "title": str,
  "description": str,
  "category": str,
  "item_type": str,
  "brand": str,
  "model_tier": str,
  "price": float,
  "material": [],
  "tecnologia": []
}}

Regras:
- Use SOMENTE informações presentes no texto
- NÃO invente dados
- Retorne UM objeto para CADA produto recebido
- NÃO inclua markdown, comentários ou texto extra
- Material e tecnologia nao podem estar vazios.
- Incluia todos os materiais e tecnologias mencionados na descricao do produto. Podem ser um, ou muitos. Nunca zero.

Produtos:
{json.dumps(batch_records, ensure_ascii=False)}
"""

    success = False
    retries = 0

    while not success and retries < MAX_RETRIES:
        try:
            time.sleep(SLEEP_BETWEEN_CALLS)

            response = model.generate_content(prompt)
            res_text = response.text.strip().replace("```json", "").replace("```", "")

            batch_result = json.loads(res_text)

            if not isinstance(batch_result, list):
                raise ValueError("Resposta não é uma lista")

            enriched_data.extend(batch_result)

            print(f"Processados produtos {start + 1} até {min(end, len(df_products))}")
            success = True

        except Exception as e:
            retries += 1
            print(f"Erro no batch {start}-{end} (Tentativa {retries}/{MAX_RETRIES})")
            time.sleep(60)

    if not success:
        print(f"Falha definitiva no batch {start}-{end}")
        for row in batch_records:
            row["material"] = "Erro Persistente"
            row["tecnologia"] = "Erro Persistente"
            enriched_data.append(row)

    # Backup a cada batch
    with open("backup_parcial.json", "w", encoding="utf-8") as f:
        json.dump(enriched_data, f, ensure_ascii=False, indent=2)

# 3. Salvamento final
with open("ecommerce_products_enriched.json", "w", encoding="utf-8") as f:
    json.dump(enriched_data, f, ensure_ascii=False, indent=4)

print("\nFINALIZADO! Dataset processado com sucesso.")