# -*- coding: utf-8 -*-
"""JSON_CSV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrKEbsJW12uHJj4lsIEjk2dizjuuCBnt
"""

import json
import csv

# Input / Output files
INPUT_JSON = "ecommerce_products_enriched.json"
OUTPUT_CSV = "ecommerce_products_enriched.csv"

# Load JSON
with open(INPUT_JSON, "r", encoding="utf-8") as f:
    data = json.load(f)

# Helper function to join list values
def join_list(value):
    if isinstance(value, list):
        return ". ".join(value)
    return value

# Prepare CSV headers from first item
fieldnames = list(data[0].keys())

# Write CSV
with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()

    for item in data:
        item["material"] = join_list(item.get("material", []))
        item["tecnologia"] = join_list(item.get("tecnologia", []))
        writer.writerow(item)

print(" CSV file created successfully:", OUTPUT_CSV)