# -*- coding: utf-8 -*-
"""Relatorio de Qualidade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLocsuyAcuP7KbeYaTgyepixEiKw690a
"""

import pandas as pd
import great_expectations as ge
import json

# Load CSVs with pandas first
products_pd = pd.read_csv('ecommerce_products.csv')
users_pd = pd.read_csv('ecommerce_users.csv')
orders_pd = pd.read_csv('ecommerce_orders.csv')
items_pd = pd.read_csv('ecommerce_items.csv')

# Convert to Great Expectations datasets
df_products = ge.from_pandas(products_pd)
df_users = ge.from_pandas(users_pd)
df_orders = ge.from_pandas(orders_pd)
df_items = ge.from_pandas(items_pd)

print("✅ Arquivos carregados com sucesso!")

# --- VALIDAÇÕES ---
# (Aqui mantivemos suas regras com os nomes de variáveis únicos)

# --PRODUTOS ---
# Regra 1 : O preço nunca pode ser negativo ou zero
res_price_prod = df_products.expect_column_values_to_be_between('price', min_value=0.01)

# Regra 2 : Não pode haver IDs de produtos nulos
res_prod_id_prod = df_products.expect_column_values_to_not_be_null('product_id')

# --- USUÁRIOS ---
# Regra 1 : E-mail deve conter o símbolo '@'
res_email = df_users.expect_column_values_to_match_regex('email', r'.+@.+\..+')

# Regra 2 : Não pode haver IDs de usuario nulos
res_user_id_user = df_users.expect_column_values_to_not_be_null('user_id')

# Regra 3 : Nome nao pode ser nulo
res_name = df_users.expect_column_values_to_not_be_null('name')

# Regra 4 : Sobrenome nao pode ser nulo
res_last_name = df_users.expect_column_values_to_not_be_null('last_name')

# --Items ---
# Regra 1 : Item_id nao pode ser nulo
res_item_id_item = df_items.expect_column_values_to_not_be_null('item_id')

# Regra 2 : Order_id nao pode ser nulo
res_order_id_item = df_items.expect_column_values_to_not_be_null('order_id')

# Regra 3 : product_id nao pode ser nulo
res_prod_id_item = df_items.expect_column_values_to_not_be_null('product_id')

# Regra 4 : unit__price nao pode ser negativo ou zero
res_unit_price = df_items.expect_column_values_to_be_between('unit_price', min_value=0.01)

# Regra 5 : subtotal nao pode ser negativo ou zero
res_subtotal = df_items.expect_column_values_to_be_between('subtotal', min_value=0.01)

# Regra 6 : quantity nao pode ser negativo ou zero
res_quantity = df_items.expect_column_values_to_be_between('quantity', min_value=1)

# --- ORDERS ---
# Regra 1 : order_id nao pode ser nulo
res_order_id_order = df_orders.expect_column_values_to_not_be_null('order_id')

# Regra 2 : Order_id nao pode ser nulo
res_user_id_order = df_orders.expect_column_values_to_not_be_null('user_id')

# Regra 3: O status deve ser um dos valores pré-definidos
res_status = df_orders.expect_column_values_to_be_in_set('status', ['delivered', 'shipped', 'processing', 'cancelled'])

# Regra 4: O status deve ser um dos valores pré-definidos
res_payment = df_orders.expect_column_values_to_be_in_set('payment_method', ['Boleto', 'Pix', 'Credit Card'])

# Regra 5 : shipping_cost nao pode ser negativo
res_shipping = df_orders.expect_column_values_to_be_between('shipping_cost', min_value=0)

# Regra 6 : total_amount nao pode ser negativo ou zero
res_total_amount = df_orders.expect_column_values_to_be_between('total_amount', min_value=1)

# 3. Gerando um resumo simples do relatório
validations = [ res_price_prod, res_prod_id_prod,
                res_email, res_user_id_user, res_name, res_last_name,
                res_item_id_item, res_order_id_item, res_prod_id_item, res_unit_price, res_subtotal, res_quantity,
                res_order_id_order, res_user_id_order, res_status, res_payment, res_shipping, res_total_amount]
success_count = sum(1 for v in validations if v['success'])

print(f"\nResultado da Validação: {success_count}/{len(validations)} testes passaram.")

# Para o relatório visual, o GE gera arquivos HTML,
# mas para o case, você pode salvar o JSON de resultado.
import json
with open('quality_report.json', 'w') as f:
    # Convertendo para um formato serializável
    results_to_save = [v.to_json_dict() for v in validations]
    json.dump(results_to_save, f, indent=4)

print("Relatório 'quality_report.json' gerado com sucesso!")

!pip uninstall great_expectations -y
!pip install great_expectations==0.18.15 -q